name: bundle

on:
  push:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'aot-magisk.zip'
          exclusions: '*.git* *.github* *.gitinore *.md'
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'aot-magisk.zip'
          path: 'aot-magisk.zip'
