name: bundle

on:
  push:
    branches:
      - main

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create zip
        run: |
          zip -r aot-magisk.zip . -x "*.git*" "*.github*" "*.gitignore" "*.md" .
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: 'aot-magisk'
          path: 'aot-magisk.zip'
